### ISSUE TITLE
"CUDA Error: Invalid Argument When Using Interactive Prompts in Docker Container"

### ISSUE THREAD

**Issue by nilsrehtanz** [coendevente/SlicerNNInteractive#37]
Thank you very much for this amazing tool! It really helps a lot! In the newest version of the Docker setup, I have this error:

When attempting to use point or scribble interactions on the SlicerNNInteractive server, operations fail with a CUDA error when creating tensors using the Docker setup.

## Environment Information
- **Docker Image**: coendevente/nninteractive-slicer-server:latest
- **CUDA Version**: 12.1.0
- **Python Version**: 3.12 (conda environment: nnInteractive)
- **GPU**: Full GPU access (not virtualized/partial)
- **Input Image Dimensions**: 797×512×512 (from server logs)
- **Operating System**: Linux (Jetstream cloud instance)

## Detailed Error
The server fails with `RuntimeError: CUDA error: invalid argument` when trying to create a CUDA tensor with `torch.zeros()` in the `_initialize_interactions` method. This happens after successfully uploading an image and attempting to add interactive prompts.

## Steps to Reproduce
1. Start the Docker container: `docker run --gpus all --rm -it -p 1527:1527 coendevente/nninteractive-slicer-server:latest`
2. Connect to the server from 3D Slicer using the nnInteractive extension
3. Upload an image (in my case, with dimensions 797×512×512)
4. Try to add a point or scribble interaction
5. Server crashes with the CUDA error shown in the stack trace

## Error Stack Trace
```
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

The error specifically occurs in:
```python
File "/opt/conda/envs/nnInteractive/lib/python3.12/site-packages/nnInteractive/inference/inference_session.py", line 140, in _initialize_interactions
  self.interactions = torch.zeros(
```

**Comment by muratmaga** [comment]
More on this.

This work fine on the JS2 fine if you can get a g3.xl instance which has a full, dedicated, bypass A100 GPU. These instances are using the regular NVIDIA driver. 

If you use any other instance, which provides slices of the GPU via the NVIDIA's GRID driver, the provided docker image is not compatible with this and doesn't seem to work. Installing into a virtual python environment without docker also fails. 

@lassoan I would highly encourage you consider updating the base docker image. Image itself says it is DEPRECATED. I am not sure. I am not entirely sure if this will the GRID driver issue, but at least it might give a path forward. Finding the full g3.xl instances is getting harder and that GPU is an overkill for this anyways. So it would be nice to be able to use the smaller instances.

**Comment by muratmaga** [comment]
I will also inquire with JS2 admins to see if it is possible there is a configuration difference. Beyond the being a GRID driver, the driver versions are idential between g3.xl and the sliced instances.

**Comment by muratmaga** [comment]
@nilsrehtanz I just noticed that you are indeed using the full instance. Your errors might be different then what I am seeing.

**Comment by pieper** [comment]
Note that the docker image was working just fine for me last week, but when I unshelved the same machine and ran the exact same command line is wasn't working for me yesterday on a JS2 g3.medium.

**Comment by muratmaga** [comment]
This is working fine with g3.xl provisioned just now fine. I upscaled up to 850x850x850 to test:

<img width="2166" alt="Image" src="https://github.com/user-attachments/assets/efac0f25-d24a-4f51-bcd1-dda79a2b74ce" />

**Comment by pieper** [comment]
You're right @muratmaga it does work on a smaller dataset, so the underlying issue is probably just a memory limitation and not a driver issue.  Using docker on the js2 g3.medium is working for me with the MRHead sample data.  But if I use crop volume with a scale factor of 0.3 I get the same stack trace and error in `torch.zeros`.

So really we just need some better error handling and feedback to the user suggesting they crop or resize (and ideally some clues as to what parameters the server's hardware will be able to support).

**Comment by lassoan** [comment]
These are very useful information! We should definitely improve the error messages. However, we need accurate examples of the exact error messages so that we can recognize and rewrite them.

-----

For example, on Windows, using a laptop RTX 3080ti, the error message caused by a too large image makes sense. I get correct segmentation results for a 651x731x731 image (CTChest resampled), but if I resample the same image it to 1140x1280x1280 then I get `DefaultCPUAllocator: not enough memory` message:

```
  File "C:\Users\andra\AppData\Local\nninteractive-server\.pixi\envs\default\Lib\site-packages\nnInteractive\inference\inference_session.py", line 154, in _background_set_image
    nonzero_idx = torch.where(image_torch != 0)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: [enforce fail at alloc_cpu.cpp:115] data. DefaultCPUAllocator: not enough memory: you tried to allocate 59607998912 bytes.
```

I guess it all depends on how deep the error is propagated from. In this case a CPU operation fails, so it is easier to capture the real root cause of the error.

-----

Do you all get the same `RuntimeError: CUDA error: invalid argument` error in `inference_session.py` line 140 `self.interactions = torch.zeros(...` when the image is too large?

**Comment by nilsrehtanz** [comment]
Thank you all for your help! I really appreciate it! The tool is really amazing, we are using it for lesion segmentation. Ron is having a field day! :)

I cropped my spine volumes to the relevant regions, and the error is gone.

@lassoan 
"RuntimeError: CUDA error: invalid argument error in inference_session.py line 140 self.interactions = torch.zeros(..." 

This is the error I get, when the image is too large

**Comment by muratmaga** [comment]
> docker on the js2 g3.medium is working for me with the MRHead sample data.

That's bizarre, because g3.l, I can't even launch the server, much less to start with the tool. @pieper Can you send me your driver version info from that instance? I wonder somehow they are differently provisioned?

**Comment by pieper** [comment]
@muratmaga my setup is the ubuntu 24.04 image on JS2 without web-desktop enabled.  Maybe you are seeing the issue where the GPU desktop conflicts with gpu docker?

```
$ nvidia-smi 
Fri Apr 25 20:25:00 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.230.02             Driver Version: 535.230.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  GRID A100X-10C                 On  | 00000000:04:00.0 Off |                    0 |
| N/A   N/A    P0              N/A /  N/A |      1MiB / 10240MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by muratmaga** [comment]
possible. Now, I have one instance that is working right off the bat, and one that doesn't :) Trying to figure out what's different about them :) But my issue definitely is not OOM, but infrastructure one.

**Comment by lassoan** [comment]
@muratmaga what is the exact error message you get? The same as @nilsrehtanz? (`RuntimeError: CUDA error: invalid argument error in inference_session.py line 140 self.interactions = torch.zeros(...`)

**Comment by muratmaga** [comment]
@lassoan my issue is very specific and not related to main issue reported here (which is ambigious OOM error). I don't want to derail this specific issue. Mine is clearly related to some obscure provisioning difference of instances between JS2 and Morphocloud (which it is based off), and I am tracking it here if you want to see. https://github.com/MorphoCloud/MorphoCloudWorkflow/issues/109
